---
spring:
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false