---
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:h2:mem:dev"
    username: sa
    password: sa
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 9011

logging:
  level:
    web: trace
    sql: trace