---
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
server:
  port: 9011
